root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-270_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M270.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M300.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M300.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M300.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-350_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M350.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-400_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M400.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-450_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M450.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M500.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M500.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M500.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-550_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M550.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-600_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M600.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-650_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M650.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M700.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M700.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M700.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-800_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M800.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-900_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M900.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1000_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1000.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1000_v1.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1000.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1100_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1100.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1200_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1200.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1300_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1300.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1400_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1400.root")'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1500_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1500.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1500_v1.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_M1500.root")'
#root -l -b -q 'mktree.cc+("Trees/tree_data.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_nominal/tree_data.root")'

root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-270_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M270.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-300_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M300.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-300_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M300.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-300_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M300.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-350_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M350.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-400_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M400.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-450_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M450.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-500_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M500.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-500_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M500.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-500_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M500.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-550_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M550.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-600_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M600.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-650_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M650.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-700_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M700.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-700_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M700.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-700_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M700.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-800_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M800.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-900_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M900.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1000_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1000.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1000_v1.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1000.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1100_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1100.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1200_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1200.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1300_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1300.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1400_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1400.root")'
root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1500_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1500.root")'
#root -l -b -q 'mktree.cc+("TreesReg/RadionToHH2G2B_M-1500_v1.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_M1500.root")'
#root -l -b -q 'mktree.cc+("TreesReg/tree_data.root","/afs/cern.ch/work/h/hebda/HggHbb/ntuples/Trees_reg/tree_data.root")'
