root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M300_RD_even.root",0)'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M700_RD_even.root",0)'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M500_RD_even.root",0)'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1000_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1000_RD_even.root",0)'
hadd -f /afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/training.root /afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/*even*

root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M300_RD_odd.root",1)'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M700_RD_odd.root",1)'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M500_RD_odd.root",1)'
root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1000_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1000_RD_odd.root",1)'
hadd -f /afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/testing.root /afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/*odd*

#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-650_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M650_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M300_v1.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M300_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1200_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1200_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-270_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M270_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-350_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M350_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-300_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M300_RD.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-450_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M450_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M500_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-400_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M400_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-550_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M550_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1000_v1.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1000_v1.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M700_RD.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1100_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1100_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_RD.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M500_RD.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-900_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M900_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-500_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M500_v1.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1500_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1500_RD.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1300_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1300_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-600_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M600_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1000_RD.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1000_RD.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1400_v2.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1400_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-1500_v1.root_0.root","/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M1500_v1.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M700_v2.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-700_v1.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M700_v1.root")'
#root -l -b -q 'mktree.cc+("Trees/RadionToHH2G2B_M-800_v2.root_0.root", "/afs/cern.ch/work/h/hebda/HggHbb/CMSSW_5_2_5/src/ggAnalysis/regression/TrainingFiles/tree_M800_v2.root")'
